apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cyrixrr/homelab-gitops.git
    targetRevision: main
    path: apps/devops-demo-api/chart
    helm:
      releaseName: devops-demo-api
      valueFiles:
        - ../values/dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
